#!/usr/bin/env python3
"""
Minimal valid PDF 1.4 writer - stdlib only, NO external deps.
Verified openable by Adobe / Chrome / Preview / macOS Preview.

Why this exists: a hand-rolled PDF that mis-computes the xref table
(byte offsets) is rejected by every reader ("file won't open").
This writer tracks each object's byte offset DURING concatenation
(offsets[onum] = len(out)), so the xref table always matches the
actual layout and readers accept the file.

Usage:
    from pdf_writer import PDF
    p = PDF()
    p.newline()
    p.fillrect(0, 760, 595, 82, 0.12)
    p.text(40, 815, "Title", 20, 'F2')
    p.text(40, 790, "Subtitle", 11, 'F1')
    ...
    data = p.build()
    open('out.pdf', 'wb').write(data)

Layout helpers (flow emulation):
    newline()       : flush current page into pages list, start a new one
    fillrect/rect   : filled/outlined rectangle (use for section bars)
    text(x,y,s,...) : absolute-positioned text; F1=Helvetica, F2=Courier
When y < ~60 call newline() and reset y (page is 842 tall).
Page objects are 6+2*i (page) and 5+2*i (content stream), fonts 3/4.
"""
import os

class PDF:
    def __init__(self):
        self.pages = []
        self._cur = None
        self.width, self.height = 595, 842  # A4

    def _esc(self, s):
        return s.replace('\\', r'\\').replace('(', r'\(').replace(')', r'\)')

    def text(self, x, y, s, size=10, font='F1'):
        self._cur.append(f"BT /{font} {size} Tf 1 0 0 1 {x} {y} Tm ({self._esc(s)}) Tj ET")

    def rect(self, x, y, w, h):
        self._cur.append(f"{x} {y} {w} {h} re S")

    def fillrect(self, x, y, w, h, gray=0.9):
        self._cur.append(f"{gray} g {x} {y} {w} {h} re f 0 g")

    def newline(self):
        if self._cur is not None:
            self.pages.append(self._cur)
        self._cur = []

    def build(self):
        if self._cur:
            self.pages.append(self._cur)
        n_pages = len(self.pages)
        objects = {}
        objects[1] = b"<< /Type /Catalog /Pages 2 0 R >>"
        kids = " ".join(f"{6 + 2*i} 0 R" for i in range(n_pages))
        objects[2] = f"<< /Type /Pages /Kids [{kids}] /Count {n_pages} >>".encode()
        objects[3] = b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>"
        objects[4] = b"<< /Type /Font /Subtype /Type1 /BaseFont /Courier >>"
        for i, pg in enumerate(self.pages):
            stream = ("\n".join(pg)).encode('latin-1')
            cid = 5 + 2*i
            pid = 6 + 2*i
            objects[cid] = stream
            objects[pid] = (f"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] "
                            f"/Resources << /Font << /F1 3 0 R /F2 4 0 R >> >> "
                            f"/Contents {cid} 0 R >>").encode()
        total_objs = 4 + 2*n_pages
        out = bytearray(b"%PDF-1.4\n")
        offsets = {}
        for onum in range(1, total_objs + 1):
            offsets[onum] = len(out)          # <-- offset tracked during concat
            body = objects[onum]
            if isinstance(body, str):
                body = body.encode('latin-1')
            is_stream = (5 <= onum <= 4 + 2*n_pages) and (onum - 5) % 2 == 0
            if is_stream:
                chunk = f"{onum} 0 obj\n<< /Length {len(body)} >>\nstream\n".encode() + body + b"\nendstream\nendobj\n"
            else:
                chunk = f"{onum} 0 obj\n".encode() + body + b"\nendobj\n"
            out += chunk
        xref_pos = len(out)
        out += f"xref\n0 {total_objs + 1}\n".encode()
        out += b"0000000000 65535 f \n"
        for onum in range(1, total_objs + 1):
            out += f"{offsets[onum]:010d} 00000 n \n".encode()
        out += f"trailer\n<< /Size {total_objs + 1} /Root 1 0 R >>\nstartxref\n{xref_pos}\n%%EOF".encode()
        return bytes(out)


if __name__ == '__main__':
    p = PDF()
    p.newline()
    p.fillrect(0, 760, 595, 82, 0.12)
    p.text(40, 815, "Demo PDF", 20, 'F2')
    p.text(40, 790, "Generated by pdf_writer.py (stdlib, no deps)", 11, 'F1')
    p.text(40, 760, "Hello, valid PDF 1.4", 10, 'F1')
    data = p.build()
    with open('demo.pdf', 'wb') as f:
        f.write(data)
    print(f"Wrote demo.pdf ({len(data)} bytes)")
