#!/usr/bin/env python3
"""Check the actual JS string being generated in the HTML"""
import urllib.request

try:
    req = urllib.request.Request('http://localhost:8765/')
    resp = urllib.request.urlopen(req)
    html = resp.read().decode('utf-8')
    
    # The HTML is generated by Python strings. Find the chevron in the HTML
    # Look for the actual onclick attribute in the generated HTML
    idx = html.find('chev')
    while idx >= 0:
        # Get surrounding context
        start = max(0, idx - 100)
        end = min(len(html), idx + 200)
        context = html[start:end]
        
        # Check if this is the onclick context
        if 'onclick' in context:
            print(f"=== Found chevron at position {idx} ===")
            print(f"Context: {context}")
            print()
            break
        
        idx = html.find('chev', idx + 1)
    
    # Now check if the generated HTML has valid JS
    # Extract the inline script
    script_start = html.find('<script>')
    script_end = html.find('</script>', script_start)
    if script_start >= 0 and script_end >= 0:
        js_content = html[script_start + 8:script_end]
        
        # Check for syntax errors
        errors = []
        
        # Check for backtick issues
        if '`collapsed`' in js_content:
            errors.append("Backtick in toggle()")
        
        # Check for unescaped quotes in HTML attribute
        if "toggle('collapsed')" in js_content and "onclick=\"event.stopPropagation();this.parentElement.parentElement.classList.toggle('collapsed')\">▼" in js_content:
            print("✅ Chevron onclick looks correct in generated HTML")
        elif 'toggle(\\'collapsed\\')' in js_content:
            print("⚠️ Potential escaping issue in generated HTML")
        
        # Check for any obvious JS syntax issues
        # Look for the openSettings function completion
        settings_end = js_content.find('function openSettings()')
        if settings_end >= 0:
            # Get the function
            func_text = js_content[settings_end:settings_end+5000]
            # Check for syntax errors
            open_tags = func_text.count('{')
            close_tags = func_text.count('}')
            print(f"\nopenSettings tag balance: {open_tags} open, {close_tags} close")
            
            # Check for any broken strings
            for i, ch in enumerate(func_text[:8000]):
                if ch == '\\' and i+1 < len(func_text):
                    next_ch = func_text[i+1]
                    if next_ch not in "'\"\\{}[];().: \n\t":
                        pass  # Just logging
        
        if errors:
            print(f"\n⚠️ Errors found: {errors}")
        else:
            print("\n✅ No obvious JS syntax errors found")

except Exception as e:
    print(f"Error: {e}")
    import traceback
    traceback.print_exc()
